name: "Fanart"
guid: "170a157f-ac6c-437a-abdd-ca9c25cebd39"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-fanart.png"
version: 10
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Scrape poster images from Fanart"
description: "Scrape poster images for movies, shows, and artists in your library."
category: "Metadata"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Fanart.dll"
changelog: |-
  - chore(deps): update dependency microsoft.extensions.http to v6 (#41) @renovate

  ### Bug Fixes ###
  - fix tv series no data (#38) @kdays

  ### CI & build changes ###
  - fix: meta ci workflows (#39) @h1dden-da3m0n
